version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - TRANSMISSION_WEB_HOME=/combustion-release/
      # - USER=
      # - PASS=
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: bridge
    environment:
      - ADVERTISE_IP="http://127.0.0.1:32400/"
      - HOSTNAME=media-server
      # - PLEX_CLAIM=
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./plex/data:/data
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"      
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      # - UMASK_SET=022 #optional
    volumes:
      - ./sonarr/config:/config
      - ./plex/tv:/tv
      - ./transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped